### ISSUE TITLE
Base colours for objects

### ISSUE THREAD

**Issue by henryseg** [mtwoodard/hypVR-Ray#28]
How does the lighting model change if the objects themselves have colours?

**Comment by roice3** [comment]
Depending on how deep we want to go here, we might want to support various types of object color. E.g. POV-Ray supports ambient, diffuse, emissive, phong, etc. in its [finish ](http://www.povray.org/documentation/3.7.0/r3_4.html#r3_4_6_3)keyword for objects.

I'm sure we'll want to keep it simple at the beginning, so maybe we just track down how raytracers calculate ambient color for objects.

**Comment by mtwoodard** [comment]
I changed the model so that there is a base color that is used to initialize the ambient component as well as affect the diffuse component. To be more specific in these lines in particular:
vec3 color = baseColor * ambient;
color += att*((diffuse*baseColor) + specular);
Currently this is not done on an object by object basis so all objects are being affected.

**Comment by mtwoodard** [comment]
I've also been trying to figure out how to get uv-coordinates for objects in the scene. I found two resources on it both [here](http://iquilezles.org/www/articles/filteringrm/filteringrm.htm) and [here](http://www.pouet.net/topic.php?which=7920&page=59). However I still need to read further on them.
