### ISSUE TITLE
Question about the scene raymarching

### ISSUE THREAD

**Issue by neozhaoliang** [mtwoodard/hypVR-Ray#69]
Hi mtwoodard: As one travels in the cells, the scene procedurally draws the cells far away, and the details are still quite good.  I'd want to know how did hypVR implement this? Since as one goes far away from the origin, the floating point precision becomes a problem, especially for rendering scene near the boundary.

**Comment by henryseg** [comment]
Hi neozhaoliang - we are using raymarching, which is a variant of raytracing. The scene is built inside of a cube. When a ray passes through the boundary of the cube, it does not enter a new cube, further away from the origin. Instead, we apply an isometry to move the ray so that it enters the original cube again. Thus, the ray never gets too far from the origin, and we don't get floating point errors. This is true unless the ray travels out towards a corner of the cube - these corners are ideal, so we again get floating point errors.

**Comment by neozhaoliang** [comment]
Thanks @henryseg , got it! I'm also writing a live honeycomb animation on shadertoy, your information is very helpful.
